create table products (id int generated by default as identity, name varchar(100) not null, description text not null, stock int not null, primary key(id));
insert into products (name, description, stock) values ('popok', 'ini popok bagus untuk bayi', 500);
insert into products (name, description, stock) values ('mie', 'ini mie bagus untuk orang dewasa', 200);
insert into products (name, description, stock) values ('permen', 'ini popok bagus untuk anak-anak', 300);

create table customers (id int generated by default as identity, name varchar(100) not null, address text not null, primary key(id));
insert into customers (name, address) values ('Budi', 'Jalan duren apel mangga');
insert into customers (name, address) values ('Andi', 'Jalan anggur stroberi apel');
insert into customers (name, address) values ('Dedi', 'Jalan jalanin aja dulu');

create table transaction (id int generated by default as identity, product_id int not null, customer_id int not null, qty int not null default 0, primary key(id));

create or replace procedure transaction(customer int, product int, quantity int)
language plpgsql as $$
begin
update products set stock = stock - quantity where products.id = product;
insert into transaction (product_id, customer_id, qty) values (product, customer, quantity);
commit;
end;$$;

create or replace procedure restock(product int, quantity int)
language plpgsql as $$
begin
update products set stock = stock + quantity where products.id = product;
commit;
end;$$;